version: '3.8'

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
    
services:
  app:
    container_name: comcamp35-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL
      - JWT_TOKEN
      - GOOGLE_CLIENT_ID
      - GOOGLE_SECRET
      - GOOGLE_CALLBACK_URL
      - FRONTEND_URL
      - APP_VERSION
    volumes:
      - '.:/usr/src/app'
    ports:
      - '4000:4000'
    networks:
      - app

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=comcamp
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data:/data'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d comcamp'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app