version: '3.8'

networks:
  app:

volumes:
  postgres_data:
  minio_data:
    
services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=comcamp
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data:/data'
  
  minio:
    image: docker.io/bitnami/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=${DB_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=comcamp